name: Security Scan (DVWA-Clone)

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  security-events: write   # SARIF upload için gerekli
  actions: read

jobs:
  sast-semgrep:
    name: SAST - Semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DVWA-Clone repo
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep (SAST)
        run: |
          semgrep --config auto --sarif --output semgrep.sarif
          echo "✅ Semgrep completed"

      - name: Upload Semgrep SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

  container-trivy:
    name: Container Scan - Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DVWA-Clone repo
        uses: actions/checkout@v4

      - name: Build DVWA Docker image
        run: docker build -t dvwa-clone:latest .

      - name: Scan DVWA image with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: dvwa-clone:latest
          format: sarif
          output: trivy.sarif
          vuln-type: 'os,library'
          # severity: 'HIGH,CRITICAL'
          ignore-unfixed: false

      - name: Upload Trivy SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif

      - name: Ensure SARIF file exists
        run: |
          if [ ! -f trivy.sarif ]; then
            echo "Trivy SARIF file not found!"
            exit 1
          fi
      
      - name: Upload Trivy SARIF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sarif
          path: trivy.sarif

  
  secret-gitleaks: 
      name: Secret Scan - Gitleaks 
      runs-on: ubuntu-latest 
      steps: 
        - name: Checkout DVWA-Clone (full history)
          uses: actions/checkout@v4
          with:
            fetch-depth: 0  # commit geçmişini tara

        - name: Install Gitleaks
          run: |
            wget https://github.com/gitleaks/gitleaks/releases/download/v8.24.3/gitleaks_8.24.3_linux_x64.tar.gz
            tar -xvf gitleaks_8.24.3_linux_x64.tar.gz
            sudo mv gitleaks /usr/local/bin/gitleaks

        - name: Run Gitleaks (Full Repo Scan)
          run: |
            gitleaks detect \
              --source . \
              --report-format sarif \
              --report-path gitleaks.sarif \
              --verbose

        - name: Upload Gitleaks SARIF to GitHub Security Dashboard
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: gitleaks.sarif




  # secret-gitleaks: 
  #   name: gitleaks
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 100
  #     - uses: gitleaks/gitleaks-action@v2
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
  #         GITLEAKS_VERSION: "8.24.3"
  #         GITLEAKS_ENABLE_UPLOAD_ARTIFACT: "true"
  #     - name: Upload Gitleaks SARIF to GitHub Security Dashboard
  #       uses: github/codeql-action/upload-sarif@v3
  #       with:
  #         sarif_file: gitleaks-result.sarif
          




  # Disabled

  # Secret Scanning with TruffleHog -  due to sarif issue
  # https://github.com/trufflesecurity/trufflehog/issues/578
  # TruffleHog:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       shell: bash
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: TruffleHog OSS
  #       id: trufflehog
  #       uses: trufflesecurity/trufflehog@main
  #       continue-on-error: true
  #       with:
  #         path: ./
  #         extra_args: --json

  #     - name: Scan Results Status
  #       if: steps.trufflehog.outcome == 'failure'
  #       run: exit 1
